version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=capstone-archive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis-dump:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  dbmate:
    image: amacneil/dbmate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/capstone-archive?sslmode=disable
      - DBMATE_WAIT=true
    depends_on:
      - postgres
    command: up
    volumes:
      - ./db:/db

  server:
    build: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/capstone-archive
      - REDIS_ADDRESS=redis:6379
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
      - redis
      - dbmate
      - auth
    ports:
      - 4000:8080

  client:
    build: ./client
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
    depends_on:
      - server
    ports:
      - 3000:3000
